package main;

import motor.Juego;

/**
 * @author DeathabtO
 */

public class DialogoJuegoNuevo extends javax.swing.JDialog {
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioDificil;
    private javax.swing.JRadioButton radioFacil;
    private javax.swing.JRadioButton radioMedio;
    private javax.swing.JRadioButton radioPersonalizado;
    private javax.swing.JSpinner spinnerAncho;
    private javax.swing.JSpinner spinnerLargo;
    private javax.swing.JSpinner spinnerMinas;
    // End of variables declaration//GEN-END:variables
	private boolean aceptar;
	private static VentanaPrincipal ventanaPrincipal;
	
	public DialogoJuegoNuevo(VentanaPrincipal parent, boolean modal){
		super(parent, modal);
		this.ventanaPrincipal = parent;
		initComponents();
		this.aceptar = false;
		try{
			this.spinnerAncho.commitEdit();
			this.spinnerLargo.commitEdit();
			this.spinnerMinas.commitEdit();
		}catch(Exception e){
			
		}
	}
	
	public boolean aceptado(){
        return aceptar;
    }
    
    public int getCantidadFilas(){
        return //((Integer)spinnerAncho.getValue()).byteValue();
        Integer.parseInt(spinnerAncho.getModel().getValue().toString());
    }
    
    public int getCantidadColumnas(){
        return //((Integer)spinnerLargo.getValue());
                Integer.parseInt(spinnerLargo.getModel().getValue().toString());
    }
    
    public int getCantidadMinas(){
        return //((Integer)spinnerMinas.getValue());
                Integer.parseInt(spinnerMinas.getModel().getValue().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spinnerLargo = new javax.swing.JSpinner();
        spinnerAncho = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        radioFacil = new javax.swing.JRadioButton();
        radioMedio = new javax.swing.JRadioButton();
        radioDificil = new javax.swing.JRadioButton();
        radioPersonalizado = new javax.swing.JRadioButton();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        spinnerMinas = new javax.swing.JSpinner();

        setTitle("Iniciar juego nuevo");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Largo:");

        spinnerLargo.setModel(new javax.swing.SpinnerNumberModel(10, 5, 100, 1));
        spinnerLargo.setEnabled(false);

        spinnerAncho.setModel(new javax.swing.SpinnerNumberModel(5, 5, 100, 1));
        spinnerAncho.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Ancho:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Minas:");

        buttonGroup1.add(radioFacil);
        radioFacil.setSelected(true);
        radioFacil.setText("Fácil");
        radioFacil.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioFacilItemStateChanged(evt);
            }
        });

        buttonGroup1.add(radioMedio);
        radioMedio.setText("Medio");
        radioMedio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioMedioItemStateChanged(evt);
            }
        });

        buttonGroup1.add(radioDificil);
        radioDificil.setText("Difícil");
        radioDificil.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioDificilItemStateChanged(evt);
            }
        });

        buttonGroup1.add(radioPersonalizado);
        radioPersonalizado.setText("Personalizado");
        radioPersonalizado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioPersonalizadoItemStateChanged(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        spinnerMinas.setModel(new javax.swing.SpinnerNumberModel(10, 5, 1000, 1));
        spinnerMinas.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(radioFacil)
                                .addGap(18, 18, 18)
                                .addComponent(radioMedio)
                                .addGap(18, 18, 18)
                                .addComponent(radioDificil)
                                .addGap(18, 18, 18)
                                .addComponent(radioPersonalizado))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spinnerLargo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spinnerMinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 22, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spinnerLargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(spinnerMinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPersonalizado)
                    .addComponent(radioDificil)
                    .addComponent(radioMedio)
                    .addComponent(radioFacil))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAceptar)
                    .addComponent(botonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void radioPersonalizadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioPersonalizadoItemStateChanged
        spinnerAncho.setEnabled(radioPersonalizado.isSelected());
        spinnerLargo.setEnabled(radioPersonalizado.isSelected());
        spinnerMinas.setEnabled(radioPersonalizado.isSelected());
    }//GEN-LAST:event_radioPersonalizadoItemStateChanged

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        this.aceptar= true;
        this.setVisible(false);
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void radioFacilItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioFacilItemStateChanged
        if(radioFacil.isSelected()){
            this.spinnerAncho.setValue(Juego.ANCHO_FACIL);
            this.spinnerLargo.setValue(Juego.LARGO_FACIL);
            this.spinnerMinas.setValue(Juego.MINAS_FACIL);
        }
    }//GEN-LAST:event_radioFacilItemStateChanged

    private void radioMedioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioMedioItemStateChanged
        if(radioMedio.isSelected()){
            this.spinnerAncho.setValue(Juego.ANCHO_MEDIO);
            this.spinnerLargo.setValue(Juego.LARGO_MEDIO);
            this.spinnerMinas.setValue(Juego.MINAS_MEDIO);
        }
    }//GEN-LAST:event_radioMedioItemStateChanged

    private void radioDificilItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioDificilItemStateChanged
        if(radioDificil.isSelected()){
            this.spinnerAncho.setValue(Juego.ANCHO_DIFICIL);
            this.spinnerLargo.setValue(Juego.LARGO_DIFICIL);
            this.spinnerMinas.setValue(Juego.MINAS_DIFICIL);
        }
    }//GEN-LAST:event_radioDificilItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoJuegoNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoJuegoNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoJuegoNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoJuegoNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoJuegoNuevo dialog = new DialogoJuegoNuevo(ventanaPrincipal, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

}
